/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LeaderboardImport } from './routes/leaderboard'
import { Route as IndexImport } from './routes/index'
import { Route as LeaderboardIndexImport } from './routes/leaderboard/index'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LeaderboardRoute = LeaderboardImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LeaderboardIndexRoute = LeaderboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeaderboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/leaderboard/': {
      id: '/leaderboard/'
      path: '/'
      fullPath: '/leaderboard/'
      preLoaderRoute: typeof LeaderboardIndexImport
      parentRoute: typeof LeaderboardImport
    }
  }
}

// Create and export the route tree

interface LeaderboardRouteChildren {
  LeaderboardIndexRoute: typeof LeaderboardIndexRoute
}

const LeaderboardRouteChildren: LeaderboardRouteChildren = {
  LeaderboardIndexRoute: LeaderboardIndexRoute,
}

const LeaderboardRouteWithChildren = LeaderboardRoute._addFileChildren(
  LeaderboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRouteWithChildren
  '/signup': typeof SignupRoute
  '/leaderboard/': typeof LeaderboardIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/leaderboard': typeof LeaderboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRouteWithChildren
  '/signup': typeof SignupRoute
  '/leaderboard/': typeof LeaderboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/leaderboard' | '/signup' | '/leaderboard/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signup' | '/leaderboard'
  id: '__root__' | '/' | '/leaderboard' | '/signup' | '/leaderboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRouteWithChildren
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRouteWithChildren,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/leaderboard",
        "/signup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/leaderboard": {
      "filePath": "leaderboard.tsx",
      "children": [
        "/leaderboard/"
      ]
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/leaderboard/": {
      "filePath": "leaderboard/index.tsx",
      "parent": "/leaderboard"
    }
  }
}
ROUTE_MANIFEST_END */
